### PR TITLE
[upload_jamf_10_23_fix] fix checking connection for Jamf Pro >= 10.23

### LINKED ISSUE #65: Anyone having login issues to Jamf Pro 10.23?
PPPC has been working fine for me until the latest Jamf Pro release 10.23, now Check Connection at Upload just doesn't do anything for me. Anyone having this problem too? Thanks.

PPPC Version 1.2.0 (1.2.0-t1588162790)
Jamf Pro 10.23.0-t1595614145

### PR DESCRIPTION
**Pull request by kkot**
Resolves #65

### CODE REVIEW

File: Source/JamfProClient.swift [hunk 1]
```diff
@@ -102,10 +111,11 @@ struct JamfProClient {
                     let major = Int(versionParts[0]),
                     let minor = Int(versionParts[1]),
                     let patch = Int(versionParts[2]) {
-                    result = (major: major, minor: minor, patch: patch)
+                    version = Version(major: major, minor: minor, patch: patch)
                 }
             }
-            completionBlock(result)
+            let connectionOk = statusCode == 200 || statusCode == 401
```
Comment (hisaac) [inline Source/JamfProClient.swift:117]: Doesn't 401 mean unauthorized? Why are we saying that connection is ok?

Comment (hisaac) [reply Source/JamfProClient.swift:117]: What about just passing the status code into the completion block directly like the `getOrganizationName` method does? Then we can decide how to handle it when we call the method in the `UploadViewController`.

**Review by hisaac — COMMENTED** [review]
Looking good @kkot! I have some questions and stylistic comments, but nothing major.

File: Source/JamfProClient.swift (hunk 1 above)
Comment (kkot) [reply Source/JamfProClient.swift]: Yes, it means unauthorized. Because we just get content of main page `https://something.jamfcloud.com` there is a login page and for some reason, JSS returns it together with code 401.

I tried to pass statusCode as you suggested but I think that this logic `connectionOk = statusCode == 200 || statusCode == 401` make more sense inside this method. When I moved it outside it was harder to understand. I changed the order of arguments thought to match `getOrganizationName`.

File: Source/View Controllers/UploadViewController.swift [hunk 2]
```diff
@@ -112,37 +112,41 @@ class UploadViewController: NSViewController {
...
-            } else {
+        client.getJamfProVersionLegacy { (possibleVersion, connectionOk) in
+            if (!connectionOk) {
                 print("Jamf Pro server is unavailable")
                 DispatchQueue.main.async {
                     self.handleCheckConnectionFailure(enforceSigning: nil)
                 }
+                return
+            }
+            var mustSign: Bool
```
[the remark this answers is not in the document]
Comment (kkot) [reply Source/View Controllers/UploadViewController.swift:123]: This way is little more readable for me and I would prefer to keep it.

File: Source/JamfProClient.swift (hunk 1 above)
Comment (hisaac) [reply Source/JamfProClient.swift]: Gotcha, that works for me. Thanks for the clarity.

File: Source/View Controllers/UploadViewController.swift [hunk 3]
```diff
@@ -112,37 +112,42 @@ class UploadViewController: NSViewController {
...
+            if let version = possibleVersion {
+                print("Jamf Pro Server: \(version.major).\(version.minor).\(version.patch)")
+                mustSign = version.major < 10
+                        || version.major == 10 && version.minor < 7
+                        || version.major == 10 && version.minor == 7 && version.patch == 0
+            } else {
+                // nil means version >= 10.23 so singing not required
```
Comment (macblazer) [inline Source/View Controllers/UploadViewController.swift:130]: Nitpick: spelling error in `signing`

Singing is never required, although it is fun.

**Review by macblazer — APPROVED** [review]
Looks good other than the one spelling error which could be fixed.

**Review by macblazer — APPROVED** [review]

**Review by watkyn — APPROVED** [review]
